### PR TITLE
Add support for compatible releases

### PR DESCRIPTION
**Pull request by stephenfin**
These are a pretty nifty feature described in PEP 440 [1]. However,
they're not supported in specfiles so we need to convert them. The
approach here is rather hacky and may well break with more convoluted
requirements, but it's a good start and better than what we have right
now (nothing).

[1] https://www.python.org/dev/peps/pep-0440/#compatible-release

### CODE REVIEW

**Comment by stephenfin** [comment]
Should have looked before I jumped. Seems #196 should do this and is far more mature.

**Comment by gordonmessmer** [comment]
Thanks, @stephenfin .  Miro approved several of my pull requests earlier this week, and once I merge those I think we can review #196 .  I'm eager to get those done, but I spent the week preparing for vacation.  I'll probably find some down time to merge those shortly, and I hope we'll get you support for compatible-release ASAP.  :)

**Comment by hroncok** [comment]
If any one of you would like to look into `=~`, the support is missing both in https://src.fedoraproject.org/rpms/pyproject-rpm-macros/blob/master/f/pyproject_buildrequires.py and https://github.com/rpm-software-management/rpm/blob/master/scripts/pythondistdeps.py#L244

**Comment by gordonmessmer** [comment]
@stephenfin I've updated #196 if you'd like to test it and make any suggestions.

**Pull request closed without merging**
