### PR TITLE
DNF API name converter

### PR DESCRIPTION
**Pull request by mcyprian**
In this PR:
-  code of name convertor based on DNF API query
- integration of new convertor
- unit tests

Tests are failing, because I haven't found the way how to get dnf into travis yet.

### CODE REVIEW

**Comment by hroncok** [comment]
Can you fix the Travis build somehow?
I guess it could be quite challenging to get dnf to Ubuntu, so just disable those tests there fo now.

**Comment by hroncok** [comment]
Dan**d**ifiedNameConvertor vs Dan**t**ifiedNameConvertor (commit message)

**Comment by hroncok** [comment]
I know pycairo is not exactly on PyPI, but this test would not pass:

``` python

class TestDandifiedNameConvertor(object):

    def setup_method(self, method):
        self.dnc = DandifiedNameConvertor('fedora')

    @pytest.mark.parametrize(('pypi_name', 'version', 'expected'), [
        ('pycairo', '2', 'pycairo'),
        ('pycairo', '3', 'python3-cairo'),
    ])
    def test_rpm_name(self, pypi_name, version, expected):
        assert self.dnc.rpm_name(pypi_name, version) == expected
```

**Comment by mcyprian** [comment]
Tests requiring DNF are skipped if module is missing, pycairo package is now part of the unit tests, passing on my local machine.

**Comment by hroncok** [comment]
LGTM

**Comment by mcyprian** [comment]
Thanks, I think this PR is ready to be merged.

**Pull request merged**
