### PR TITLE
 Handle PyPI rate limit of one request per second. 

### PR DESCRIPTION
**Pull request by gordonmessmer**
https://bugzilla.redhat.com/show_bug.cgi?id=1892478

### CODE REVIEW

**Comment by jamescassell** [comment]
Thanks for the fix. I assume this is why COPR is failing python PyPI builds. RH bug is private, unfortunately, otherwise I'd subscribe.

**Comment by gordonmessmer** [comment]
@jamescassell  Do you have a link to the logs of any of those failed builds?

**Comment by jamescassell** [comment]
This PR works around the issue for me when running it by hand. The COPR error was a different message IIRC.

**Comment by gordonmessmer** [comment]
This issue is resolved in v3.3.5

**Comment by gordonmessmer** [comment]
... but do let me know if the COPR errors look like they're related to a pyp2rpm problem.

**Pull request closed without merging**
