### PR TITLE
Add a workaround for setup.py that prints

### PR DESCRIPTION
**Pull request by hroncok**
Fixes https://github.com/fedora-python/pyp2rpm/issues/180

Hopefully the tests will not break, I'm trying now locally.

If it passes, I'll add Python 3.7 to the test docker.

### CODE REVIEW

**Comment by hroncok** [comment]
@QuLogic would you be able to review this? Especially if it helps you, but looking at the code would be nice as well.

Note: Ideally I would add a test for failed metadata_extractor report, to check it indeed reports the failed json to load, but given the state of this project, I'd rather not. I've added an integration test for paperwork-backend.

**Comment by hroncok** [comment]
The integration test failures on 3.7 are unrelated, but related to Sphinx. I don't have the strength to solve them, maybe just skip them?

**Comment by QuLogic** [comment]
This works for me on paperwork-backend and paperwork. I don't see anything wrong except some "misuse" of the logging API, but that's an existing problem all over the code base.

**Comment by hroncok** [comment]
@encukou there are unrelated Sphinx package names test failures.

 * we can skip them and never get back to them again
 * or merge as is and probably never get beck to them either, but at least there will be no false sense of safety

While broken tests on CI can seriously hurt a project, the tests were broken here for months, having this on life support I rather be reminded about the failing tests once a year when we change stuff rather than no knowing about it.

(Also, actually investigating and fixing the failures is out of my possibilities now and given the state of the project, I think that's OK.)

Thanks.

**Review by encukou — APPROVED** [review]
That makes sense. I'm also unlikely to spend any significant time on pyp2rpm.

**Pull request merged**
