### PR TITLE
configure PYTHONPATH when building docs with sphinx

### PR DESCRIPTION
**Pull request by TomasTomecek**
I'm assuming that tests will break; will address those issues once CI finishes

### CODE REVIEW

**Comment by TomasTomecek** [comment]
Honestly, I have no idea why the tests fail, since I changed the spec files in `test_data`.

**Comment by mcyprian** [comment]
Spec file examples using DNF based name_convertor have to be updated as well:
- python-Jinja2_base_dnfnc.spec
- python-Jinja2_dnfnc.spec
- python-Jinja2_epel6_dnfnc.spec
- python-Jinja2_epel7_dnfnc.spec
- python-sphinx_dnfnc.spec) 


In `python-Jinja2_autonc.spec` there is `doc` vs` docs` difference:
`
At index 73 diff: u'PYTHONPATH=${PWD} sphinx-build-3 docs html' != 'PYTHONPATH=${PWD} sphinx-build-3 doc html'`

You can use [commands from .travis.yml ](https://github.com/fedora-python/pyp2rpm/blob/master/.travis.yml#L6) to run test suite locally.

**Comment by TomasTomecek** [comment]
Thanks Michal, good catch.

Should be okay now.

**Comment by mcyprian** [comment]
Looks good to me, thank you.

**Comment by TomasTomecek** [comment]
Thanks! I hope this is gonna be useful for more people and not just me.

**Comment by hroncok** [comment]
BTW https://github.com/fedora-modularity/conu/pull/99

**Pull request merged**
